### ISSUE TITLE
Blur effect changes when zooming in or out

### ISSUE THREAD

**Issue by LimesKey** [LimesKey/limeskey.com#3]
In `+page.svelte`, the blur effect for the background changes when I zoom in or out. Here is the CSS code,

```css
                    .background {
                        width: 100%;
                        height: 100%;
                        display: fill;
                        background-size: cover;
                        position: fixed;
                        background-image: url("/assets/cat.jpg");
                        background-repeat: no-repeat;
                        background-color: aqua;
                        z-index: -2;
                        background-position: 90%, 60%;
                    }

                    .background:after {
                        content: "";
                        width: 100%;
                        height: 100%;
                        backdrop-filter: blur(10px);
                        pointer-events: none;
                        position: fixed;
                        white-space: nowrap;
                        overflow: hidden;
                        display: flex;
 ```
